"[#] ci/cd":
 - '.github/*'
 - '.github/**/*'

"[#] doc":
 - '*.md'
 - 'doc/*'
 - 'doc/**/*'
 - 'examples/**/*'

"[#] hseq":
 - 'hseq/*'
 - 'hseq/**/*'

"[#] optics":
 - 'optics/*'
 - 'optics/**/*'

"[#] pipe":
 - 'pipe/*'
 - 'pipe/**/*'

"[#] pure":
 - 'pure/*'
 - 'pure/**/*'

"[#] trait":
 - 'trait/*'
 - 'trait/**/*'
