//
// Code generated by `golem` package
// Source: github.com/fogfish/golem/crypto/crypto.go
// Time: 2020-02-03 17:43:48.514444 +0000 UTC
//
//
// Copyright (C) 2020 Dmitry Kolesnikov
//
// This file may be modified and distributed under the terms
// of the MIT license.  See the LICENSE file for details.
// https://github.com/fogfish/golem
//

package identity

import (
	"encoding/json"

	"github.com/fogfish/golem/crypto/cipher"
	
)

// AnyT is generic definition of sensitive structures
type Crypto Identity

// UnmarshalJSON implements automatic decryption of data
func (value *Crypto) UnmarshalJSON(b []byte) (err error) {
	type Referable Crypto

	var cryptotext string
	if err = json.Unmarshal(b, &cryptotext); err != nil {
		return
	}

	text, err := cipher.Default.Decrypt(cryptotext)
	if err != nil {
		return
	}

	var gen Referable
	if err = json.Unmarshal(text, &gen); err != nil {
		return
	}

	*value = Crypto(gen)
	return
}

// MarshalJSON implements automatic encryption of sensitive strings during data marshalling.
func (value Crypto) MarshalJSON() (bytes []byte, err error) {
	type Referable Crypto

	binary, err := json.Marshal(Referable(value))
	if err != nil {
		return
	}

	text, err := cipher.Default.Encrypt(binary)
	if err != nil {
		return
	}

	return json.Marshal(text)
}

// PlainText returns plain text value
func (value Crypto) PlainText() Identity {
	return Identity(value)
}
